import re

feature_mapping = {'African': 30,
 'American (Traditional)': 29,
 'Arabic': 34,
 'Argentine': 29,
 'Art Galleries': 1,
 'Art Schools': 1,
 'Art Space Rentals': 1,
 'Arts & Crafts': 1,
 'Arts & Entertainment': 1,
 'Asian Fusion': 2,
 'Australian': 29,
 'Bagels': 3,
 'Bakeries': 3,
 'Barbeque': 4,
 'Bars': 5,
 'Basque': 31,
 'Beauty & Spas': 6,
 'Beer Bar': 5,
 'Beer, Wine & Spirits': 28,
 'Belgian': 31,
 'Bistros': 7,
 'Boating': 16,
 'Books, Mags, Music & Video': 1,
 'Bookstores': 1,
 'Bowling': 16,
 'Brasseries': 7,
 'Brazilian': 29,
 'Breakfast & Brunch': 26,
 'Breweries': 28,
 'Brewpubs': 28,
 'British': 31,
 'Bubble Tea': 20,
 'Buffets': 8,
 'Burgers': 237,
 'Butcher': 29,
 'Cafes': 10,
 'Cafeteria': 10,
 'Cajun/Creole': 29,
 'Candy Stores': 14,
 'Cantonese': 12,
 'Caribbean': 34,
 'Caterers': 16,
 'Champagne Bars': 5,
 'Cheese Shops': 13,
 'Chicken Shop': 11,
 'Chicken Wings': 11,
 'Chinese': 12,
 'Cocktail Bars': 5,
 'Coffee & Tea': 9,
 'Coffee Roasteries': 9,
 'Congee': 12,
 'Convenience Stores': 26,
 'Conveyor Belt Sushi': 33,
 'Cooking Schools': 6,
 'Creperies': 14,
 'Cultural Center': 1,
 'Dance Clubs': 5,
 'Delicatessen': 13,
 'Delis': 13,
 'Desserts': 14,
 'Dim Sum': 12,
 'Diners': 28,
 'Dive Bars': 5,
 'Do-It-Yourself Food': 15,
 'Donuts': 14,
 'Farmers Market': 16,
 'Farms': 16,
 'Fashion': 1,
 'Fast Food': 17,
 'Ferries': 16,
 'Filipino': 32,
 'Fish & Chips': 31,
 'Fishing': 16,
 'Florists': 16,
 'Fondue': 31,
 'Food': 35,
 'Food Court': 17,
 'Food Delivery Services': 13,
 'Food Stands': 17,
 'French': 31,
 'Fuzhou': 12,
 'Gastropubs': 5,
 'German': 31,
 'Gluten-Free': 18,
 'Greek': 31,
 'Grocery': 25,
 'Hainan': 12,
 'Hakka': 32,
 'Halal': 34,
 'Hawaiian': 29,
 'Hawker Centre': 17,
 'Health Markets': 26,
 'Herbs & Spices': 27,
 'Himalayan/Nepalese': 32,
 'Home Decor': 25,
 'Hong Kong Style Cafe': 12,
 'Hookah Bars': 5,
 'Horseback Riding': 16,
 'Hot Dogs': 17,
 'Hot Pot': 19,
 'Hunan': 12,
 'Ice Cream & Frozen Yogurt': 14,
 'Imported Food': 35,
 'Indian': 32,
 'Indonesian': 32,
 'International': 31,
 'International Grocery': 25,
 'Irish': 31,
 'Irish Pub': 5,
 'Italian': 31,
 'Izakaya': 33,
 'Japanese': 33,
 'Japanese Curry': 33,
 'Juice Bars & Smoothies': 20,
 'Karaoke': 16,
 'Kebab': 30,
 'Korean': 32,
 'Kosher': 34,
 'Landmarks & Historical Buildings': 21,
 'Latin American': 29,
 'Live/Raw Food': 32,
 'Local Flavor': 35,
 'Lounges': 28,
 'Mah Jong Halls': 16,
 'Malaysian': 32,
 'Meat Shops': 25,
 'Mediterranean': 34,
 'Mexican': 29,
 'Middle Eastern': 34,
 'Mini Golf': 16,
 'Modern European': 31,
 'Mongolian': 32,
 'Moroccan': 30,
 'Music Venues': 16,
 'Nightlife': 16,
 'Noodles': 22,
 'Organic Stores': 25,
 'Pakistani': 32,
 'Pan Asian': 32,
 'Pancakes': 14,
 'Parking': 23,
 'Parks': 16,
 'Patisserie/Cake Shop': 14,
 'Pekinese': 12,
 'Personal Shopping': 25,
 'Peruvian': 29,
 'Pet Services': 24,
 'Pet Stores': 24,
 'Pets': 24,
 'Pharmacy': 35,
 'Photographers': 16,
 'Pizza': 31,
 'Pool & Billiards': 16,
 'Portuguese': 31,
 'Print Media': 1,
 'Professional Services': 25,
 'Public Plazas': 25,
 'Pubs': 5,
 'Ramen': 33,
 'Restaurants': 35,
 'Robatayaki': 4,
 'Russian': 31,
 'Salad': 26,
 'Sandwiches': 26,
 'Scandinavian': 31,
 'Seafood': 35,
 'Shanghainese': 12,
 'Shared Office Spaces': 16,
 'Shopping': 25,
 'Shopping Centers': 25,
 'Singaporean': 32,
 'Social Clubs': 16,
 'Soup': 35,
 'Spanish': 31,
 'Specialty Food': 35,
 'Specialty Schools': 35,
 'Sports Bars': 5,
 'Sports Clubs': 5,
 'Sri Lankan': 32,
 'Steakhouses': 29,
 'Street Vendors': 17,
 'Supernatural Readings': 35,
 'Sushi Bars': 33,
 'Szechuan': 12,
 'Taiwanese': 12,
 'Tapas Bars': 5,
 'Tapas/Small Plates': 26,
 'Tea Rooms': 9,
 'Teochew': 12,
 'Teppanyaki': 33,
 'Tex-Mex': 29,
 'Thai': 32,
 'Themed Cafes': 10,
 'Traditional Chinese Medicine': 35,
 'Turkish': 32,
 'Udon': 33,
 'Ukrainian': 31,
 'Vegan': 27,
 'Vegetarian': 27,
 'Venues & Event Spaces': 16,
 'Vietnamese': 32,
 'Waffles': 14,
 'Wedding Planning': 35,
 'Whiskey Bars': 5,
 'Wholesale Stores': 25,
 'Wine Bars': 5,
 'Wineries': 28}


def extract_name(x):

  tmp = re.sub('-[\d]$', '', str(x))
  tmp = re.sub('-\u9999\u6e2f$', '', tmp)
  tmp = re.sub('-', ' ', tmp)

  return tmp


def flatten_dictlist(x):
  return [item['title'] for item in x if 'title' in item]


def flatten_list(llist):
    flat_list = []

    for element in llist:
      flat_list.append(element[0])

    return flat_list

